### ISSUE TITLE
b9partswitch issue with BDB Pioneer SNAP19 RTG

### ISSUE THREAD

**Issue by Beetlecat** [Grimm-Aerospace/GrimmModlets#1]
**BDBKerbalismUpdate**

Just a single B9PS warning at game startup pointing to this part. The config for the SNAP19 in the patch seems to match all the others, no obvious typos, etc.

I'm running BDB from the newest dev version on GitHub, possibly they've tweaked the part recently? There are a couple partswitch modules on the part itself:

https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/ProbeExpansion/Pioneer/bluedog_Pioneer_SNAP19.cfg

**Comment by Grimmas** [comment]
Thanks! It's probably because I'm trying to delete ModuleGenerator indiscriminately, and that module is actually inside of the B9 switch. I'll look into fixing it properly.

**Comment by Grimmas** [comment]
Fixed. Also now supports the B9 switch properly, so that the Extended version produces more EC (Kerbalism interface doesn't immediately update but it should be visible when launching or switching editors).

**Comment by Beetlecat** [comment]
Awesome! TY!
