### ISSUE TITLE
BDB Kerbalism creates a 2nd RTG

### ISSUE THREAD

**Issue by Gordon-Dry** [Grimm-Aerospace/GrimmModlets#3]
GameData\KerbalismConfig\Support\Bluedog.cfg does :FOR[KerbalismDefault] and adds
```
	MODULE
	{
		name = Emitter
		radiation = 0.0000017775
	}
	 
  	MODULE:NEEDS[ProfileDefault]
	{
		name = ProcessController
		resource = _RTG
		title = RTG
		capacity = 0.66      (or any other number)
		running = true
		toggle = false
	} 

	!MODULE[ModuleGenerator] {}
	!MODULE[ModuleCoreHeat] {} 
```
Afterwards GameData\GrimmAerospace\GrimmModlets\BDBKerbalismUpdate\BDB_RTGs.cfg does :AFTER[KerbalismDefault] and adds
```
  MODULE
  {
    name = ProcessController
    resource = _RTG
    title = #KERBALISM_RTG_title//RTG
    capacity = 0.25
    running = true
    toggle = false
  }
  
  MODULE
  {
    name = Emitter
    radiation = 0.00001388875 // 0.05 rad/h
  }

  !MODULE[ModuleGenerator] {}
  !MODULE[ModuleCoreHeat] {}
```

1st: why?
2nd: why different?

**Comment by Gordon-Dry** [comment]
I suggest an edit instead of a new node generation.

**Comment by Grimmas** [comment]
I looked in the Kerbalism master branch but [did not find the duplicate you mention](https://github.com/Kerbalism/Kerbalism/blob/master/GameData/KerbalismConfig/Support/Bluedog.cfg). Maybe it's from your own patch or another compatibility patch?
